"""
Stage 5: 分类标注
=================
基于关键词规则为商户分类。规则从原 fix_categories.py 完整迁移。

输入:  data/kb_internal.csv
输出:  原地更新 category 字段
"""

import csv
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import INTERNAL_FILE, KB_INTERNAL_COLUMNS

# ============================================================================
# KEYWORD-BASED CATEGORY RULES
# Each rule: (category, [list of keyword strings to match])
# Keywords are checked as case-insensitive substrings
# ============================================================================

RULES = []

def rule(category, *keywords):
    RULES.append((category, [kw.lower() for kw in keywords]))

# ---- GAMBLING ----
rule('Gambling',
    'lotto', 'lottery', 'lotteries', 'tab betting', 'tab wagering',
    'sportsbet', 'bet365', 'betfair', 'neds', 'ladbrokes', 'unibet',
    'pointsbet', 'dabble', 'playup', 'betr', 'palmerbet', 'betdeluxe',
    'picklebet', 'draftstars', 'moneyball', 'bet nation',
    'tatts', 'tattslotto', 'ozlotto', 'golden casket', 'tabcorp',
    'gambling', 'betting agency',
    'central lotto', 'carrum downs lotto', 'fourways lotto',
    'grand boulevard lotteries', 'joondalup lottery', 'melton station lotto',
    'vic park convenience & lotto',
)

# ---- DINING OUT ----
rule('Dining Out',
    'restaurant', 'cafe', 'café', 'bistro', 'diner', 'eatery', 'brasserie',
    'pizzeria', 'pizza', 'sushi', 'ramen', 'noodle', 'kebab', 'pide',
    'dumpling', 'dim sum', 'yum cha',
    'burger', 'chicken shop', 'chicken takeaway',
    'seafood restaurant', 'seafood takeaway', 'fish & chip', 'fish and chip',
    'fisho', 'fish shop', 'fish factory',
    'takeaway', 'take away', 'fast food', 'food truck', 'food van', 'food cart',
    'bakery', 'bakehouse', 'patisserie', 'pastry', 'cake shop', 'pie shop',
    'doughnut', 'donut', 'ice cream', 'gelato', 'gelateria',
    'sandwich', 'subway restaurant', 'subway store',
    'bbq', 'barbeque', 'barbecue', 'hot bread',
    'taco', 'burrito', 'mexican restaurant', 'quesadilla',
    'tavern', 'pub', 'brewery', 'brewing', 'distillery', 'winery', 'cellar door',
    'wine bar', 'beer bar', 'cocktail bar', 'whiskey bar', 'gin bar',
    'bottle shop', 'liquor shop', 'bottlemart', 'bottle-o', 'bottleo',
    'drive through bottle', 'drive bottle',
    'barista', 'espresso', 'cappuccino', 'latte', 'flat white',
    'coffee shop', 'coffee house', 'coffee roaster cafe',
    'tea house', 'tea shop', 'tea room', 'tea bar',
    'chatime', 'gong cha', 'sharetea', 'starbucks', 'gloria jean',
    'coffee club', 'hudsons coffee', 'degani', 'zarraffas', 'dome cafe',
    'maccas', 'mcdonald', 'hungry jack', 'kfc restaurant', 'dominos pizza',
    'nandos', 'guzman', 'zambrero', 'grill\'d', 'grilld', 'oporto',
    'red rooster', 'chicken treat', 'chicken chef', 'el jannah',
    'charlies chicken', 'chargrill charlie',
    'boost juice', 'top juice', 'sumo salad', 'soul origin',
    'oliver brown', 'max brenner', 'san churro', 'ben & jerry',
    'bakers delight', 'brumby', 'michels patisserie', 'donut king',
    'krispy kreme', 'muffin break', 'pie face', 'ferguson plarre',
    'catering company', 'catering service', 'function catering',
    'poke bowl', 'acai', 'smoothie bar', 'juice bar', 'salad bar',
    'chocolatier', 'fudge shop', 'confectionery shop', 'candy shop',
    'banh mi', 'banhmi', 'pho restaurant', 'thai restaurant',
    'chinese restaurant', 'indian restaurant', 'japanese restaurant',
    'korean restaurant', 'malaysian restaurant', 'indonesian restaurant',
    'italian restaurant', 'greek restaurant', 'lebanese restaurant',
    'turkish restaurant', 'afghan restaurant',
    'food court', 'food hall', 'food market stall', 'food precinct',
    'public bar', 'sports bar', 'front bar', 'public house',
    'ramen bar', 'sushi bar', 'poke bar',
    'hogs breath', 'crust gourmet pizza', 'getta burger',
    'essential coffee cafe', 'achieve cafe pro', 'bite size coffee',
    'coffee club wagga', 'south albury takeaway', 'river cruz cafe',
    'chatterbox cafe', 'dymocks cafe', 'hogs breath cafe',
    'maru grill house', 'logan city tavern', 'torotoro ramen bar',
    'first batch coffee', 'claisebrook bar',
    'bonfire bread', 'blendz & beanz', 'all day cravings cafe',
    'ramis pizza & manoosh', 'premier mobile food',
    'mccarthys bread', 'new seasons patisserie',
    'the bakeologist', 'the spirited goat', 'batter n crumbz',
    'far east restaurant', 'simple hospitality', 'ever hospitality',
    'bueno hospitality', 'alpha hospitality',
    'h&c urban winery', 'bar management', 'la royale patisserie',
    'the hot bird',
    'stellarossa', 'coco & rye', 'mr gelato by matteo c', 'messina gelato',
    'shire coffee bean', 'mobile cafe',
    'yamba bread shop', 'village green hotel', 'harwood hotel',
    'hotel bistro', 'hotel bar', 'hotel pub', 'beer garden',
    'coffs hotel', 'falveys hotel', 'kent town hotel', 'crown hotel',
    'naracoorte hotel', 'grand terminus hotel', 'belvedere hotel',
    'kooringal hotel', 'ocean beach hotel', 'kalangadoo hotel',
    'crown and anchor hotel', 'highpoint hotel', 'railway hotel beaudesert',
    'waterloo bay hotel', 'bororen hotel motel',
    'uber eats', 'ubereats', 'doordash', 'menulog', 'deliveroo',
    'uber delivery', 'food delivery app',
)

# ---- ENTERTAINMENT ----
rule('Entertainment',
    'rsl', 'rsm club', 'returned services', 'returned soldiers',
    'bowling club', 'bowls club', 'lawn bowls',
    'golf club', 'golf course', 'golf links', 'country club',
    'leagues club', 'workers club', 'diggers club', 'memorial club',
    'services club', 'community club', 'citizens club',
    'football club', 'soccer club', 'rugby club', 'cricket club',
    'netball club', 'hockey club', 'tennis club', 'squash club',
    'surf club', 'surf life saving', 'slsc', 's.l.s.c', 'lifesaving club',
    'yacht club', 'sailing club', 'rowing club', 'fishing club',
    'aero club', 'flying club', 'gliding club',
    'racing nsw', 'racing victoria', 'racing queensland',
    'greyhound racing', 'harness racing', 'thoroughbred racing',
    'jockey club', 'turf club', 'race club', 'racecourse', 'race course',
    'cinema', 'movie theatre', 'drive-in', 'imax',
    'hoyts', 'event cinemas', 'village cinema', 'reading cinema',
    'dendy', 'palace cinema', 'sunset cinema',
    'bowling alley', 'ten pin', 'tenpin', 'amf bowling', 'zone bowling',
    'go-kart', 'gokart', 'go kart', 'paintball', 'laser tag',
    'escape room', 'mini golf', 'putt putt', 'mini putt',
    'timezone', 'arcade',
    'amusement park', 'theme park', 'water park', 'aqua park',
    'fun park', 'play centre', 'playcentre', 'inflatable',
    'bounce trampoline', 'trampoline park',
    'indoor trampoline', 'gravityx', 'inflatable world',
    'play centre', 'playcentre', 'indoor play',
    'live music venue', 'concert venue', 'nightclub', 'night club',
    'comedy club', 'jazz club', 'karaoke',
    'showground', 'show ground', 'equestrian centre',
    'polo club', 'croquet club',
    'tattersalls club', 'cavanough racing', 'subiaco football',
    'hazelbrook bowling', 'ipswich rsl', 'curlewis golf',
    'nyngan golf', 'south tweed sports', 'surfers paradise surf',
    'shore beach club', 'yarraville club', 'st albans sports club',
    'marrickville golf', 'royal adelaide golf', 'broadbeach bowls',
    'mitcham football', 'cowboys leagues', 'thirteenth beach golf',
    'brookwater golf', 'sebastopol bowling', 'kootingal moonbi rsl',
    'merrylands rsl', 'coonamble bowling', 'harrington bowling',
    'golf park sanctuary', 'golf broken hill', 'southport bowls',
    'theatre royal', 'frankston rsl',
    'cabarita beach slsc', 'nick ryan racing', 'anderson racing',
    'ciaron maher racing', 'sutton racing', 'bairnsdale rsl',
    'redcliffe dolphins', 'brothers rlfc',
    'eastlake youth centre', 'helensvale play',
    'inflatable playcentre',
)

# ---- TRAVEL ----
rule('Travel',
    'motel', 'accommodation', 'resort', 'backpacker', 'hostel',
    'caravan park', 'carapark', 'holiday park', 'tourist park',
    'camping ground', 'rv park', 'motor camp',
    'campervan', 'motorhome',
    'airline', 'airways', 'jetstar', 'qantas', 'virgin australia',
    'rex airlines', 'regional express',
    'flight centre', 'flight center', 'travel agent', 'travel agency',
    'tourism', 'visitor centre', 'visitor center', 'tour operator', 'tour guide',
    'booking.com', 'expedia', 'wotif', 'trivago', 'tripadvisor',
    'stayz', 'airbnb', 'hotels.com', 'lastminute',
    'cruise', 'carnival cruise', 'royal caribbean', 'p&o cruise',
    'car hire', 'car rental', 'rental car', 'europcar',
    'thrifty car', 'budget car', 'redspot',
    'comfort inn', 'quality inn', 'best western', 'novotel', 'ibis hotel',
    'hilton', 'marriott', 'hyatt', 'sofitel', 'mercure',
    'quest apartment', 'quest hotel', 'quest serviced',
    'sebel', 'mantra', 'crown towers', 'crown metropol', 'crown plaza',
    'holiday inn', 'park hyatt', 'shangri-la', 'four seasons',
    'intercontinental', 'ritz-carlton', 'radisson', 'westin',
    'pullman', 'peppers resort', 'rydges', 'travelodge', 'formule',
    'ibis budget', 'breakfree', 'oaks hotel', 'oaks resort',
    'serviced apartment', 'apartment hotel', 'boutique hotel',
    'inn motel', 'lodge accommodation',
    'holiday rental', 'holiday unit', 'holiday flat', 'beach house rental',
    'airport transfer', 'airport shuttle', 'airport parking',
    'vehicle rental', 'hire car',
    'redcape hotel', 'the standard hotel', 'royal hotel bala',
    'stockmans motel', 'west coaster motel', 'vauxhall inn',
    'holiday management', 'reflections holiday',
    'heathcote hotel', 'the bridge hotel', 'heywood hotel',
    'hotel rottnest',
    'gwydir carapark', 'kolora lodge', 'hughenden hotels',
    'vital care accommodation',
)

# ---- GROCERIES ----
rule('Groceries',
    'supermarket', 'super market', 'grocer', 'grocery', 'groceries',
    'woolworths', 'woolies', 'woolworth',
    'coles supermarket', 'coles store',
    'aldi supermarket', 'aldi store',
    'iga supermarket', 'iga store', 'iga mercato', 'iga heathridge',
    'foodland', 'foodworks', 'supabarn', 'supa barn', 'costco',
    'spar supermarket', 'spar express', 'spar store',
    'harris farm', 'thomas dux', 'romeo food', 'drakes supermarket',
    'butcher', 'butchery', 'meat shop', 'meat store', 'meat market',
    'halal meat', 'meat centre',
    'poultry shop', 'chicken shop',
    'fish market', 'seafood market', 'fishmonger',
    'fruit & veg', 'fruit and veg', 'fruit shop', 'vegetable shop',
    'green grocer', 'produce store', 'fruit supply', 'fruit market',
    'vege shop', 'farmers market', 'fresh produce', 'fresh food market',
    'deli', 'delicatessen', 'continental deli', 'european deli',
    'gourmet deli', 'janus deli',
    'bws store', 'bws liquor', 'liquorland', 'dan murphy',
    'vintage cellars', 'first choice liquor', 'thirsty camel',
    'cellarbrations', 'liqour store', 'booze shop',
    'bottle shop', 'bottle-o', 'bottleo', 'bottlemart',
    'bottle mart', 'liquor shop', 'liquor store', 'liquor express',
    'corks cellar', 'pittwater cellars', 'condellos liquor',
    'heathridge liquor', 'bailey bottle', 'beckenham liquor',
    'bottlemart redcliffe', 'bottlemart melton', 'bottlemart pakenham',
    'bottlemart stones', 'bottlemart highgate', 'bottlemart',
    'drive through bottle', 'drive bottle', 'liquor warehouse',
    'convenience store', 'convenience shop', 'corner store', 'corner shop',
    'milk bar', 'mixed business', 'think convenience', 'aussie convenience',
    '7-eleven', '7 eleven', 'night owl', 'nightowl',
    'ezyplus', 'ezy mart', 'ezy convenience',
    'bp shop', 'ampol food',
    'food store', 'food market', 'food emporium', 'food centre',
    'organic market', 'health food store', 'wholefoods', 'whole foods',
    'continental store', 'asian grocer', 'indian grocer',
    'mediterranean grocer', 'middle eastern grocer',
    'african grocer', 'latin grocer', 'international foods',
    'ritchies supermarket', 'ritchies store',
    'food emporium', 'tuckerbox', 'foodary', 'foodmart', 'food barn',
    'mega fresh', 'fresh packed', 'fresh market', 'lockyer produce',
    'sutcliffe meats', 'wilkinson seafood', 'supafin seafood',
    'angelo st market', 'tek supermarket', 'alligator brand',
    'jiayuan supermarket', 'champions iga', 'ida street supermarket',
    'bairnsdale fruit supply', 'mh convenience stores',
    'vanstone produce', 'infruit',
    'elizabeth street grocer',
)

# ---- RETAIL ----
rule('Retail',
    'retail store', 'retail shop', 'retail outlet', 'retail group',
    'clothing store', 'clothing shop', 'apparel', 'fashion store', 'fashion shop',
    'garment', 'footwear store', 'footwear shop', 'shoe store', 'shoe shop',
    'sneakers store', 'boots store',
    'jewellery store', 'jewelry store', 'jeweller', 'pendant', 'necklace',
    'bracelet', 'ring', 'earrings', 'diamond', 'gemstone',
    'watch store', 'watch shop', 'timepiece',
    'sunglass store', 'sunglass shop', 'sunglass hut', 'eyewear',
    'specsavers', 'opsm', 'laubman', 'oscar wylee', 'bailey nelson',
    'handbag store', 'purse', 'wallet', 'leather goods', 'luggage store',
    'electronics store', 'electrical store', 'appliance store',
    'whitegoods', 'white goods',
    'jb hi', 'jb hifi', 'jbhifi', 'harvey norman', 'good guys',
    'bing lee', 'joyce mayne', 'domayne', 'betta electrical',
    'retravision', 'radio rentals', 'the good guys',
    'furniture store', 'furniture shop', 'furnishing', 'homewares',
    'home wares', 'manchester', 'bedding', 'linen', 'mattress store',
    'bed shop', 'sofa shop', 'lounge shop',
    'ikea', 'freedom furniture', 'nick scali', 'fantastic furniture',
    'amart furniture', 'focus on furniture', 'pillow talk', 'adairs',
    'bed bath n table', 'domayne furniture', 'forty winks',
    'sleepys', 'sleep maker', 'beds r us', 'fantastic',
    'spotlight store', 'lincraft', 'fabric store', 'fabric shop',
    'haberdashery', 'sewing store',
    'officeworks', 'office works', 'staples store',
    'office supply', 'stationery store', 'stationery shop',
    'newsagency', 'newsagent', 'paper shop', 'typo', 'kikki k', 'smiggle', 'muji',
    'newsxpress', 'nextra', 'nextra news', 'lotto & news', 'news & lotto',
    'news & tobacco', 'news & gift', 'news gifts', 'news central', 'post news',
    'news post', 'news agency', 'news extra', 'internews',
    'news emporium', 'news and gifts', ' news',  # 'XXX News' pattern for suburban newsagencies
    'bookstore', 'bookshop', 'book store', 'book shop',
    'dymocks', 'qbd books', 'readings books', 'abbey bookstore',
    'berkelouw', 'gleebooks', 'kinokuniya', 'booktopia',
    'toy store', 'toy shop', 'toys r us', 'toyworld', 'toy world',
    'mr toys', 'toymate', 'lego store',
    'sports store', 'sports shop', 'sports outlet',
    'rebel sport', 'anaconda', 'decathlon', 'bcf',
    'boating camping fishing', 'kathmandu', 'mountain designs',
    'macpac', 'paddy pallin', 'snowys', 'wild earth',
    'florist', 'flower shop', 'flower store', 'roses only',
    'bloom flower', 'bouquet', 'petal flower',
    'garden centre', 'garden center', 'nursery plant',
    'plant shop', 'plant store', 'garden supply', 'garden store',
    'hardware store', 'hardware shop', 'bunnings', 'mitre 10',
    'home hardware', 'stratco', 'total tools', 'sydney tools',
    'toolmart', 'trade tools',
    'paint shop', 'paint store', 'paint centre',
    'taubmans', 'dulux', 'wattyl', 'bristol paint',
    'tobacconist', 'tobacco shop', 'tobacco store', 'tobacco station',
    'vape shop', 'vape store', 'cigar shop', 'smoke mart', 'smokemart',
    'freechoice', 'cignall', 'tsg tobacco',
    'gift shop', 'gift store', 'giftware', 'present shop',
    'homeware store', 'kitchenware store', 'lifestyle store',
    'novelty store', 'souvenir shop',
    'pet shop', 'pet store', 'pet warehouse', 'petbarn', 'petstock',
    'pet circle', 'best friends pet',
    'party shop', 'party store', 'party supply', 'balloon shop',
    'costume shop', 'fancy dress',
    'pawn shop', 'pawnbroker', 'cash converters',
    'second hand shop', 'pre-loved', 'vintage store', 'vintage shop',
    'op shop', 'thrift store', 'thrift shop',
    'salvos store', 'vinnies shop', 'red cross shop', 'lifeline shop',
    'music shop', 'music store', 'guitar shop', 'guitar store',
    'drum shop', 'dj store', 'record store', 'vinyl store',
    'phone shop', 'phone store', 'mobile shop', 'mobile store',
    'phone accessories', 'mobile accessories',
    'computer shop', 'computer store', 'laptop shop',
    'apple store', 'microsoft store',
    'dfo outlet', 'factory outlet', 'clearance outlet',
    'online shopping', 'online store', 'online shop', 'online retail',
    'e commerce store',
    'beginning boutique', 'blue bungalow', 'the iconic', 'asos', 'showpo',
    'pretty little thing', 'boohoo', 'missguided', 'shein',
    'ozsale', 'catch.com', 'kogan', 'temple & webster',
    'mydeal', 'dealsdirect', 'crazysales',
    'cotton on', 'bonds store', 'sportsgirl', 'seed heritage',
    'country road', 'witchery', 'trenery', 'portmans', 'just jeans',
    'jay jays', 'peter alexander', 'dotti', 'jacqui e', 'review',
    'forever new', 'ally fashion', 'glassons', 'supre', 'factorie',
    'universal store', 'general pants', 'princess polly',
    'petal & pup', 'shieke', 'aere', 'dissh', 'st fiche',
    'bec & bridge', 'camilla & marc', 'zimmermann', 'alice mccall',
    'aje', 'rachel gilbert', 'saba store', 'cue clothing',
    'veronika maine', 'sass & bide', 'lorna jane', 'lululemon',
    'active truth', 'nimble activewear', 'pe nation', 'stax',
    'muscle nation', 'ryderwear', 'elite eleven',
    'chemist warehouse', 'priceline', 'mecca cosmetics', 'sephora',
    'ulta beauty', 'lush cosmetics', 'the body shop',
    'adore beauty', 'ry skin', 'kevin murphy', 'aveda',
    'kerastase', 'moroccanoil', 'ghd hair', 'dyson store',
    'skechers', 'aesop store', 'flowers whisperer', 'sawa tobacco',
    'fruitique wholesale', 'the fish factory',
    'cashmere village', 'sweet dreams', 'civic group',
    'joe wagner group', 'healey group', 'hardline group',
    'bertolini group', 'pumpa manufacturing', 'pacific manufacturing',
    'patrick auto group', 'b&d group',
    'direct imports', 'platinum products', 'unique metals',
    'total precast systems',
    'bridgewater wash house', 'sportspower',
    'alligator brand', 'next gen foods', 'odum food group',
    'bunting group', 'vuly play group', 'urban kitchens',
    'adelaide premium', 'angliss',
    'roses only', 'haighs chocolates', 'haighs', 'haigh australia', 'york street furniture',
    'your choice mattress', 'furnx warehouse', 'becson furniture',
    'blue bungalow', 'beginning boutique',
    'the styling stable',
)

# ---- DEPARTMENT STORES ----
rule('Department Stores',
    'big w', 'kmart', 'target australia', 'target store', 'target shop',
    'best&less', 'best & less', 'myer', 'david jones', 'harris scarfe',
    'department store', 'variety store', 'discount variety', 'discount store',
    'dollar store', 'cheap store',
    'the reject shop', 'cheap as chips', 'choice the discount',
    'red dot store', 'shiploads', 'crazy clarks', 'hot dollar',
    'dollar king', 'dollar tree',
    'variety store', 'variety shop', 'variety supper',
    'variety discount', 'variety bargain', 'variety warehouse',
    'one stop variety', 'super bargain', 'bargain centre', 'bargain center',
    'price busters', 'hot bargain', 'got it discount',
    'neighbours variety', 'neighbors variety',
    'dimmey', 'daiso', 'miniso', 'howards storage world',
)

# ---- HEALTH ----
rule('Health',
    'medical centre', 'medical center', 'medical clinic', 'medical practice',
    'medical group', 'medical service', 'medical specialist',
    'doctor surgery', 'doctor clinic', 'gp clinic', 'gp practice',
    'general practice', 'family practice', 'family doctor',
    'health centre', 'health center', 'health clinic', 'health service',
    'health care', 'healthcare', 'community health',
    'primary health', 'allied health', 'rural health',
    'indigenous health', 'aboriginal health',
    'women\'s health', 'womens health', 'men\'s health', 'mens health',
    'children\'s health', 'childrens health', 'youth health',
    'family health', 'sexual health', 'reproductive health',
    'public health', 'population health', 'preventive health',
    'occupational health', 'environmental health',
    'hospital', 'private hospital', 'public hospital',
    'day surgery', 'day procedure', 'surgical centre', 'surgical center',
    'emergency department', 'ambulance', 'paramedic', 'first aid',
    'dental clinic', 'dental centre', 'dental center', 'dental care',
    'dental surgery', 'dentist', 'orthodontic', 'endodontic',
    'oral health', 'oral surgery', 'dental laboratory',
    'dentures', 'prosthodontic',
    'pharmacy', 'chemist', 'chempro', 'chemplus', 'chemart', 'chem mart',
    'chemist warehouse', 'priceline pharmacy', 'terry white', 'terrywhite',
    'my chemist', 'amcal', 'guardian pharmacy', 'blooms chemist',
    'soul pattinson', 'wholelife pharmacy', 'discount chemist',
    'pharmacy 4 less', 'pharmacy less', 'pharmacy plus',
    'chemist discount', 'national pharmacy', 'pharmaplus',
    'pharmasave', 'pharmore', 'direct chemist', 'online chemist',
    'simple chemist', 'budget chemist', 'value chemist',
    'express chemist', 'super chemist', 'chemist outlet',
    'chemist superstore', 'chemist connection', 'chemist king',
    'chemist club', 'chemist direct',
    'pharmaceutical', 'pharma company', 'pharmacology',
    'physiotherapy', 'physio', 'physical therapy', 'physiotherapist',
    'chiropractic', 'chiropractor', 'osteopath', 'osteopathy',
    'pathology lab', 'radiology', 'imaging centre',
    'x-ray', 'ultrasound', 'mri scan', 'ct scan', 'sonography',
    'mammography', 'nuclear medicine',
    'optometry', 'optometrist', 'optical store', 'optics store',
    'eyecare', 'eye care', 'eye test', 'spectacles', 'glasses',
    'contact lens', 'opsm', 'specsavers optical', 'laubman & pank',
    'oscar wylee', 'bailey nelson', 'eyecare plus', 'eyecare partners',
    'vision centre', 'vision center', 'vision express', 'vision direct',
    'vision care', 'optical superstore', 'eyemasters',
    'complete eyecare', 'total eyecare', 'advanced eyecare',
    'premier eyecare', 'precise eyecare', 'perfect vision',
    'psychology', 'psychologist', 'psychiatry', 'psychiatrist',
    'mental health', 'counselling', 'counsellor',
    'therapy', 'therapist', 'psychotherapy', 'psychotherapist',
    'clinical psychology', 'behavioural therapy', 'behavioral therapy',
    'cognitive therapy', 'dbt therapy', 'cbt therapy', 'emdr therapy',
    'trauma counselling', 'grief counselling',
    'relationship counselling', 'family therapy', 'couples therapy',
    'art therapy', 'music therapy', 'play therapy',
    'occupational therapy', 'speech therapy', 'speech pathology',
    'aba therapy', 'early intervention',
    'podiatry', 'podiatrist', 'foot care clinic', 'orthotics', 'biomechanics',
    'dietitian', 'dietician', 'nutritionist', 'nutrition', 'dietetics',
    'audiology', 'audiologist', 'hearing clinic', 'hearing aid',
    'hearing care', 'hearing solutions', 'hearing life',
    'connect hearing', 'amplifon', 'bloom hearing', 'national hearing',
    'hearing australia', 'australian hearing',
    'acupuncture', 'chinese medicine', 'traditional medicine',
    'herbalist', 'naturopath', 'naturopathy', 'homeopath', 'homeopathy',
    'ayurveda', 'ayurvedic', 'reiki', 'reflexology',
    'shiatsu', 'myotherapy', 'remedial massage', 'remedial therapy',
    'complementary medicine', 'integrative medicine',
    'holistic health', 'alternative medicine', 'functional medicine',
    'nursing service', 'nurse', 'aged care', 'elderly care', 'senior care',
    'residential care', 'palliative care', 'hospice',
    'disability care', 'disability support', 'ndis',
    'home care service', 'community care', 'personal care service',
    'in-home care', 'domiciliary care',
    'supported accommodation', 'supported living',
    'assisted living', 'independent living',
    'retirement living', 'retirement village', 'nursing home',
    'veterinary', 'vet clinic', 'vet hospital', 'vet practice',
    'vet surgery', 'vet centre', 'vet center', 'vet care', 'vet service',
    'animal hospital', 'animal clinic', 'animal emergency',
    'animal referral', 'greencross vet', 'vetwest', 'vetpath',
    'pet emergency', 'small animal hospital', 'cat hospital',
    'dog hospital', 'equine hospital', 'horse vet',
    'livestock vet', 'rural vet', 'country vet', 'mobile vet',
    'house call vet', 'after hours vet',
    'hcf health', 'bupa health', 'medibank', 'nib health', 'hbf health',
    'gmhba', 'defence health', 'australian unity health',
    'teachers health', 'nurses health', 'police health',
    'emergency services health', 'st lukes health', 'latrobe health',
    'westfund', 'peoplecare', 'transport health', 'phoenix health', 'cbhs',
    'healthscope', 'ramsay health', 'healthe care', 'health scope',
    'primary health care', 'forhealth', 'healius',
    'sonic healthcare', 'clinical labs', 'qml pathology',
    'dhm pathology', 'laverty pathology', 'acl pathology',
    'melbourne pathology', 'clnpath', 'south eastern pathology',
    'western diagnostic',
    'endoscopy', 'gastroenterology', 'cardiology', 'neurology',
    'oncology', 'orthopedic', 'orthopaedic', 'rheumatology',
    'urology', 'gynecology', 'gynaecology', 'obstetrics',
    'paediatrics', 'pediatrics', 'geriatrics', 'ophthalmology',
    'ent specialist', 'ear nose throat', 'respiratory medicine',
    'pulmonology', 'nephrology', 'endocrinology',
    'haematology', 'hematology', 'immunology', 'allergy clinic',
    'infectious disease', 'pain management clinic', 'sleep clinic',
    'rehabilitation centre', 'rehab centre',
    'family planning clinic', 'fertility clinic', 'ivf clinic',
    'reproductive medicine', 'pregnancy care', 'antenatal',
    'postnatal', 'midwife', 'midwifery', 'obstetric',
    'aboriginal health service', 'aboriginal medical service',
    'aboriginal community controlled', 'ams health', 'acchs', 'amss',
    'skin cancer clinic', 'skin check', 'dermatology', 'dermatologist',
    'mole check', 'mole map', 'skin doctor', 'skin renewal', 'skin health',
    'st albans endoscopy', 'gidgee healing', 'fieldwork health',
    'spectrum health', 'providence health', 'fresenius medical',
    'aidacare', 'blue marble health', 'oplus health',
    'pegasus health', 'godrich health', 'kindred health',
    'linear clinical research', 'orion health', 'nord arc hospital',
    'easy pharmacy', 'thrive pharmacy', 'kallangur dental',
    'active care nursing', 'ausdocs medical', 'absolute footcare',
    'five good friends', 'optometry australia', 'catholic healthcare',
    'ethical nursing', 'the foot care clinic',
    'healthscope operations', 'queensland health gladstone',
    'battery hill vet', 'armajun aboriginal health',
    'pharmascope', 'allergy first', 'infinity qcare',
    'davange care', 'inspire allied health', 'global medical',
    'home at heart', 'burpengary aged care', 'bide with care',
)

# ---- AUTOMOTIVE ----
rule('Automotive',
    'automotive', 'auto repair', 'auto service', 'auto electrical',
    'auto electrician', 'car electrician', 'vehicle electrician',
    'auto sparky', 'car sparky', 'auto mechanic', 'auto parts',
    'auto recycler', 'auto dismantler', 'auto salvage', 'auto glass',
    'auto aircon', 'auto air con', 'auto technik', 'auto association',
    'auto barn', 'auto pro', 'auto transmissions',
    'mechanic', 'mechanical repair', 'mechanical service',
    'tyre', 'tire', 'tyrepower', 'tyre power', 'bridgestone',
    'goodyear', 'dunlop', 'michelin', 'pirelli', 'continental tyre',
    'yokohama', 'hankook', 'kumho', 'toyo', 'falken',
    'bob jane', 'beaurepaires', 'beaurepairs', 'jax tyres',
    'city tyres', 'quick fit', 'mr tyre', 'tyres & more',
    'tyres plus', 'discount tyres', 'cheap tyres', 'budget tyres',
    'tyre shop', 'tyre store', 'tyre centre', 'tyre center',
    'tyre depot', 'tyre warehouse', 'tyre kingdom', 'tyre world',
    'tyre zone', 'tyre mart', 'tyre sales', 'tyre service',
    'tyre & auto', 'tyre & mechanical', 'tyre & wheel',
    'apache wholesale tyres', 'country tyres',
    'exhaust shop', 'exhaust repair', 'muffler shop',
    'brake repair', 'brake service', 'clutch repair', 'clutch service',
    'gearbox repair', 'transmission repair',
    'radiator repair', 'radiator service', 'steering repair',
    'suspension repair',
    'panel beater', 'panel beating', 'panel shop', 'panel repair',
    'panel works', 'panel doctor', 'panel specialist',
    'crash repair', 'smash repair', 'collision repair',
    'dent repair', 'dent removal', 'scratch repair', 'bumper repair',
    'car wash', 'car detailing', 'car cleaning', 'car polish',
    'car groom', 'car care', 'car protection', 'ceramic coating',
    'paint protection', 'paint correction',
    'petrol station', 'fuel station', 'diesel station',
    'gas station', 'service station', 'filling station',
    'fuel stop', 'petrol stop', 'gasoline station',
    'ampol', 'bp petrol', 'bp fuel', 'shell petrol', 'shell fuel',
    'caltex', 'mobil petrol', 'mobil fuel',
    'puma energy', 'puma fuel', 'united petroleum', 'metro petrol',
    'metro fuel', 'speedway fuel', '7-eleven fuel', '7 eleven fuel',
    'bp shop', 'ampol service station', 'ampol服务站',
    'coles express', 'woolworths fuel',
    'eg group', 'viva energy', 'otr fuel', 'otr petrol',
    'autobahn', 'autopro', 'auto pro', 'autobarn', 'auto barn',
    'super cheap auto', 'supercheap auto', 'repco',
    'autocrew', 'mtaq', 'mta motor',
    'wrecker', 'wrecking', 'dismantler', 'auto recycler',
    'car recycler', 'auto dismantler', 'car dismantler',
    'auto wreck', 'car wreck', 'auto salvage', 'car salvage',
    'scrap car', 'scrap metal yard',
    'auto parts recycler', 'auto parts used',
    'tow truck', 'tow service', 'tow company', 'tow business',
    'tow operator', 'tow alliance', 'tow fleet',
    'motorcycle repair', 'motorbike repair',
    'harley davidson', 'triumph motorcycle',
    'ducati', 'kawasaki', 'suzuki motorcycle', 'yamaha motorcycle',
    'honda motorcycle', 'honda motorbike', 'honda bike',
    'car dealer', 'car sales', 'car yard', 'car dealership',
    'car mart', 'car supermarket', 'used cars', 'new cars',
    'prestige cars', 'luxury cars', '4wd centre', '4x4 centre',
    'ute sales', 'pickup sales', 'truck sales',
    'commercial vehicle sales', 'fleet sales', 'fleet disposal',
    'government auctions', 'car auctions', 'vehicle auctions',
    'pickles auctions', 'manheim', 'grays online',
    'car city', 'carsales', 'drive.com.au', 'carsguide',
    'car advice', 'which car', 'redbook', 'red book',
    'glass\'s guide', 'car history', 'car report', 'car check',
    'car inspection', 'vehicle inspection', 'pre-purchase inspection',
    'window tint', 'windscreen repair', 'windscreens replacement',
    'auto glass', 'car glass', 'vehicle glass',
    'obrien glass', 'novus glass', 'instant windscreens',
    'battery world', 'battery house', 'battery centre', 'battery center',
    'batteries plus', 'car battery', 'auto battery', 'vehicle battery',
    'nrma battery', 'rac battery', 'racv battery', 'racq battery',
    'rac roadside', 'racv roadside', 'racq roadside',
    'raa roadside', 'nrma roadside', 'roadside assist',
    'breakdown assist', 'motor association', 'auto association',
    'ultratune', 'ultra tune', 'mycar', 'my car service',
    'lube mobile', 'oil change', 'lube & tune',
    'precision auto', 'auto technik', 'bosch car service',
    'mta service', 'repco authorised', 'repco service',
    'brakes plus', 'muffler & brake', 'brake & clutch',
    'brake & front', 'brake & steering', 'brake & suspension',
    'pedders', 'carline', 'midas auto', 'abs auto', 'abs brakes',
    'car aircon', 'car air con', 'auto aircon', 'auto air con',
    'vehicle aircon', 'air conditioning auto',
    'natrad', 'adi radiator', 'cooling specialist',
    'radiator repair', 'radiator service', 'radiator shop',
    'performance car parts', 'performance auto parts',
    'performance exhaust', 'tuning chip', 'remap ecu',
    'performance engine', 'performance suspension',
    'performance brakes', 'performance tyres',
    'brown davis auto', 'mount gambier automobile',
    'dandy exhaust', 'fortress collision',
    'beenleigh wreck', 'action spares',
    'rosco chevron', 'murrell tyres', 'active vehicle rentals',
    'south coast auto', 'image autospa',
    'cardiff gas station', 'mechanical vegetation',
    'track and diesel',
)

# ---- HOME IMPROVEMENT ----
rule('Home Improvement',
    'builder', 'building company', 'building service', 'construction',
    'contractor', 'contracting', 'renovation', 'renovate', 'home extension',
    'granny flat', 'dual occupancy', 'townhouse builder',
    'unit development', 'property development', 'land development',
    'carpenter', 'carpentry', 'joiner', 'joinery', 'cabinet maker',
    'cabinetmaker', 'furniture maker', 'custom furniture',
    'floor sanding', 'timber floor', 'floorboard', 'floor installation',
    'floor laying', 'flooring contractor', 'carpet layer', 'carpet install',
    'vinyl floor', 'laminate floor', 'engineered floor',
    'hybrid floor', 'bamboo floor', 'parquetry',
    'plumber', 'plumbing', 'gas fitter', 'gasfitting', 'gas plumber',
    'drainer', 'drainage', 'blocked drain', 'drain clean',
    'pipe relining', 'pipe repair', 'pipe install',
    'hot water system', 'water heater', 'solar hot water',
    'heat pump hot water', 'gas hot water', 'electric hot water',
    'tankless water', 'continuous flow hot water',
    'backflow prevention', 'thermostatic mixing valve',
    'water filter', 'water purifier', 'water treatment', 'water softener',
    'rainwater tank', 'water tank', 'sewer', 'septic',
    'waste water', 'effluent', 'tradewaste', 'sanitary', 'sanitation',
    'electrician', 'electrical contractor', 'electrical service',
    'electrical company', 'electrical repair', 'electrical install',
    'electrical maintenance',
    'roofer', 'roofing', 'roof repair', 'roof restoration',
    'roof replacement', 'roof cleaning', 'roof painting', 'roof plumber',
    'metal roof', 'tile roof', 'colorbond', 'color bond',
    'guttering', 'gutter clean', 'gutter guard', 'gutter protection',
    'downpipe', 'fascia board', 'barge board', 'eaves', 'soffit',
    'whirlybird', 'roof ventilation', 'skylight', 'roof window', 'velux',
    'painter', 'painting contractor', 'decorator', 'decorating',
    'interior painting', 'exterior painting', 'spray painting',
    'industrial painting', 'commercial painting',
    'domestic painting', 'residential painting',
    'roof painting', 'fence painting', 'wall painting', 'ceiling painting',
    'texture coating', 'protective coating', 'epoxy coating',
    'powder coating', 'sand blasting', 'abrasive blasting',
    'grit blasting', 'soda blasting', 'water blasting',
    'pressure cleaning', 'pressure washing', 'high pressure clean',
    'hydro blasting', 'hydro jetting', 'hydro excavation',
    'plasterer', 'plastering', 'gyprock', 'gyprocking', 'drywall',
    'drywaller', 'dry wall', 'ceiling fixer', 'ceiling installer',
    'sheetrock', 'fibrous plaster', 'solid plaster',
    'venetian plaster', 'polished plaster', 'lime plaster',
    'clay plaster', 'earth plaster',
    'rendering', 'renderer', 'cement render', 'acrylic render',
    'texture coat', 'bagging', 'bag & paint',
    'tiler', 'tiling', 'tile install', 'tile repair', 'tile removal',
    'waterproofing', 'water proofing', 'waterproof membrane',
    'shower repair', 'shower install', 'shower renovation',
    'bathroom renovation', 'bathroom remodel', 'bathroom makeover',
    'bathroom install', 'wet area sealing', 'balcony repair',
    'bricklayer', 'bricklaying', 'brick layer', 'brickie',
    'stone mason', 'stonemason', 'masonry', 'blocklayer', 'block layer',
    'stonework', 'brickwork', 'blockwork',
    'retaining wall', 'garden wall', 'feature wall',
    'fireplace', 'chimney', 'brick repair', 'brick cleaning',
    'concreter', 'concreting', 'concrete service', 'concrete contractor',
    'concrete repair', 'concrete cutting', 'concrete polishing',
    'concrete grinding', 'concrete sealing', 'concrete resurfacing',
    'concrete paving', 'concrete driveway', 'concrete slab',
    'concrete floor', 'concrete wall', 'concrete pool',
    'concrete patio', 'concrete footing', 'concrete foundation',
    'restumping', 're-stumping', 'underpinning', 'resin injection',
    'crack repair', 'crack injection', 'joint repair',
    'landscaper', 'landscaping', 'landscape design',
    'landscape architect', 'landscape construction',
    'landscape maintenance', 'gardener', 'landscape supply',
    'landscape material', 'landscape rock', 'landscape stone',
    'gravel supply', 'soil supply', 'mulch supply', 'compost',
    'topsoil', 'sand supply', 'pebble supply', 'paver supply',
    'sleeper supply', 'retaining wall supply',
    'irrigation system', 'sprinkler system', 'drip irrigation',
    'garden lighting', 'outdoor lighting', 'pathway lighting',
    'deck builder', 'decking contractor', 'pergola builder',
    'patio builder', 'outdoor living', 'outdoor kitchen',
    'bbq area', 'fire pit', 'water feature', 'pond builder',
    'fencer', 'fencing contractor', 'fence installer', 'fence repair',
    'fence builder', 'fence specialist', 'timber fence',
    'colorbond fence', 'steel fence', 'aluminium fence',
    'pool fence', 'security fence', 'picket fence',
    'chain wire fence', 'chain mesh fence',
    'glazier', 'glazing', 'glass repair', 'glass install',
    'glass replacement', 'glass fitting', 'glass service',
    'glass specialist', 'shopfront glass', 'window glass',
    'shower screen', 'glass splashback', 'mirror install',
    'balustrade', 'pool fence glass', 'security glass',
    'safety glass', 'toughened glass', 'laminated glass',
    'double glazing', 'insulated glass', 'low-e glass',
    'handyman', 'handy man', 'home maintenance', 'property maintenance',
    'odd jobs', 'home repair', 'general repair', 'general maintenance',
    'building maintenance', 'facility maintenance',
    'strata maintenance', 'body corporate maintenance',
    'cleaner', 'cleaning service', 'cleaning company', 'cleaning business',
    'cleaning contractor', 'commercial cleaning', 'domestic cleaning',
    'residential cleaning', 'office cleaning', 'window cleaning',
    'high pressure cleaning', 'pressure cleaning',
    'industrial cleaning', 'factory cleaning', 'warehouse cleaning',
    'bond cleaning', 'end of lease cleaning', 'vacate cleaning',
    'pest control', 'pest management', 'pest inspection',
    'termite inspection', 'termite barrier', 'termite treatment',
    'termite protection', 'termimesh',
    'spider control', 'cockroach control', 'rodent control',
    'rat control', 'mice control', 'possum removal',
    'ant control', 'flea control', 'tick control',
    'bed bug control', 'mosquito control',
    'building inspection', 'pre-purchase building inspection',
    'building & pest', 'building report',
    'door installer', 'door repair', 'door service', 'door company',
    'door specialist', 'automatic door', 'auto door',
    'roller door', 'sectional door', 'panel lift door',
    'tilt door', 'garage door', 'industrial door',
    'fire door', 'security door', 'screen door',
    'sliding door', 'stacking door', 'folding door',
    'bifold door', 'bi-fold door', 'cavity door',
    'gate installer', 'gate repair', 'automatic gate',
    'auto gate', 'electric gate', 'motorised gate',
    'sliding gate', 'swing gate', 'driveway gate',
    'security gate', 'pedestrian gate', 'pool gate',
    'blind installer', 'shutter installer', 'awning installer',
    'curtain installer', 'curtain repair', 'curtain service',
    'curtain company', 'curtain specialist', 'curtain shop',
    'blind store', 'shutter store', 'awning store',
    'roller blind', 'roman blind', 'venetian blind',
    'vertical blind', 'panel glide blind',
    'plantation shutter', 'honeycomb blind',
    'day & night blind', 'double roller blind',
    'sunscreen blind', 'blockout blind', 'blackout blind',
    'sheer curtain', 'voile curtain', 'drapes', 'drapery',
    'asbestos removal', 'asbestos testing', 'asbestos inspection',
    'asbestos disposal', 'asbestos management', 'asbestos survey',
    'demolition', 'demolisher', 'deconstruction',
    'site clearance', 'site cut', 'earthmoving', 'earth moving',
    'excavation', 'excavator', 'digger hire',
    'bulldozer', 'backhoe', 'bobcat', 'skid steer',
    'loader machine', 'grader', 'scraper',
    'dump truck', 'tipper truck', 'roller compactor',
    'trencher', 'drilling contractor', 'boring contractor',
    'piling contractor', 'pile driving',
    'retaining contractor', 'shoring contractor',
    'rock breaking', 'rock drilling', 'hammer breaker',
    'jackhammer', 'auger drilling', 'post hole drilling',
    'scaffolding', 'scaffold', 'access equipment',
    'ewp hire', 'elevated work platform', 'cherry picker',
    'scissor lift', 'boom lift', 'forklift',
    'heating contractor', 'cooling contractor',
    'air conditioning', 'airconditioning', 'air con', 'aircon',
    'hvac', 'ventilation', 'ducted air', 'duct cleaning',
    'split system', 'reverse cycle', 'evaporative cooling',
    'gas heating', 'hydronic heating', 'underfloor heating',
    'heat pump', 'geothermal heating', 'refrigerated cooling',
    'mechanical services', 'mechanical contractor',
    'refrigeration service', 'refrigeration repair',
    'refrigeration install', 'refrigeration contractor',
    'cool room', 'coolroom', 'freezer room', 'cold room',
    'cold storage', 'walk-in cooler', 'walk-in freezer',
    'display fridge', 'cabinet fridge', 'glass door fridge',
    'solar panel installer', 'solar energy company',
    'solar power system', 'solar system installer',
    'solar pv', 'solar photovoltaic', 'solar battery',
    'solar inverter', 'solar charger',
    'pool builder', 'pool construction', 'pool installer',
    'pool repair', 'pool service', 'pool maintenance',
    'pool shop', 'pool supply', 'pool fencing',
    'pool pump', 'pool filter', 'pool chlorinator',
    'pool heating', 'pool cleaner', 'pool robot',
    'spa pool', 'swim spa', 'plunge pool',
    'welder', 'welding', 'fabrication', 'fabricator',
    'metal fabrication', 'steel fabrication',
    'aluminium fabrication', 'aluminum fabrication',
    'sheet metal', 'boilermaker', 'boiler maker',
    'metal worker', 'ironworker', 'iron worker',
    'blacksmith', 'metal art', 'metal furniture',
    'steel work', 'structural steel', 'light gauge steel',
    'shed builder', 'shed installer', 'shed constructor',
    'shed company', 'shed supply', 'shed retail',
    'garage shed', 'workshop shed', 'farm shed',
    'kitchen maker', 'kitchen manufacturer', 'kitchen installer',
    'kitchen renovation', 'kitchen remodel', 'kitchen makeover',
    'kitchen design', 'kitchen joinery', 'kitchen cabinetry',
    'kitchen cabinet', 'kitchen benchtop', 'kitchen bench top',
    'kitchen splashback', 'stone benchtop', 'marble benchtop',
    'granite benchtop', 'quartz benchtop', 'caesarstone',
    'building design', 'drafting', 'draftsman', 'draftsperson',
    'architectural drafting', 'cad design', 'building designer',
    'residential design', 'house design', 'home design',
    'architect', 'architecture firm', 'architecture practice',
    'surveyor', 'surveying', 'land survey', 'cadastral survey',
    'engineering survey', 'construction survey', 'set out survey',
    'civil engineering', 'structural engineering',
    'geotechnical engineering', 'mechanical engineering',
    'electrical engineering', 'hydraulic engineering',
    'fire engineering', 'acoustic engineering',
    'environmental engineering', 'façade engineering',
    'facade engineering', 'building services engineering',
    'construction engineering', 'mining engineering',
    'infrastructure engineering',
    'steeline roofing', 'aspen pumps', 'ddh1 drilling',
    'q pools spas', 'forlico excavati', 'deepwater pools',
    'benno civil plumbing', 'allans pool shop',
    'armstrong bricklaying', 'bj vidler construction',
    'koa construction', 'jme engineering',
    'ash refrigeration', 'dynamic door services',
    'rooforce', 'cooling brothers', 'essential trades',
    'shoringco', 'advanced aqua blasting',
    'kleen duct australia', 'complete coolroom',
    'mid west irrigation', 'bedrock landscaping',
    'de-construct', 'wilson facades', 'mlh concrete',
    'cairns quality homes', 'dr leak plumbing',
    'see us maintenance services', 'advanced engineering',
    'rushway refrigeration', 'perrott painting',
    'hardrok engineer', 'sabdia construction',
    'navaska construction', 'loughbawn construction',
    'tk formbuild constructions', 'combined plumbing',
    'elite elevators', 'total precast systems',
    'gate automation', 'coenen building',
    'woodeson excavations', 'legion drilling',
    'codmac engineering', 'hunter buildings',
    'breakaway concrete', 'mca engineering',
    'integrity formwork', 'sydney security',
    'amg security', 'raker security',
    'aligned trades', 'facade management',
    'forlico excavati', 'dynamic door services',
    'jme engineering', 'clarke civils', 'castles slipform',
    'resinject', 'capital asphalt', 'sandridge roads',
    'trueform frames', 'local plant hire', 'select coatings',
    'kristom coaters', 'belkblast', 'prime packaging',
    'track and diesel', 'coastal letting',
)

# ---- TRANSPORT ----
rule('Transport',
    'transport company', 'transport service', 'logistics', 'freight',
    'courier', 'haulage', 'trucking', 'truck company', 'truck service',
    'truck driver', 'truck line', 'truck fleet',
    'road transport', 'road freight', 'line haul',
    'long haul', 'short haul', 'local delivery',
    'express delivery', 'same day delivery', 'next day delivery',
    'overnight delivery', 'bulk haul', 'bulk transport',
    'heavy haul', 'heavy haulage', 'oversize transport',
    'wide load transport', 'pilot vehicle', 'escort vehicle',
    'removalist', 'removal company', 'removal service',
    'moving company', 'moving service', 'mover',
    'relocation company', 'furniture removal', 'house removal',
    'office removal', 'piano removal', 'interstate removal',
    'local removal', 'country removal', 'backload', 'backloads',
    'taxi', 'cab', 'uber', 'didi', 'ola rideshare',
    'rideshare', 'ride share', 'ride hailing',
    'limousine', 'limo', 'chauffeur',
    'maxi taxi', 'maxi cab', 'wheelchair taxi',
    'water taxi', 'air taxi', 'helicopter charter',
    'private jet', 'executive car service', 'corporate car',
    'airport transfer', 'airport shuttle', 'hotel transfer',
    'myki', 'go card', 'opal card', 'smartrider', 'metrocard',
    'public transport card', 'transit card',
    'bus company', 'bus service', 'bus charter', 'bus hire',
    'bus transport', 'bus transit', 'bus line', 'bus depot',
    'coach company', 'coach service', 'coach charter',
    'coach hire', 'coach transport', 'coach travel', 'coach tour',
    'train service', 'railway service', 'rail company',
    'railcorp', 'metrotrain', 'metro train', 'v/line', 'vline',
    'nsw trainlink', 'queensland rail', 'aurizon',
    'tram service', 'light rail service',
    'ferry service', 'ferries', 'water transport',
    'harbour ferry', 'river ferry', 'car ferry',
    'shipping company', 'ship operator', 'stevedoring', 'stevedore',
    'port operator', 'port authority', 'container terminal',
    'container depot', 'container park', 'container transport',
    'container logistics', 'intermodal', 'inland port', 'dry port',
    'bond store', 'customs broker', 'customs agent',
    'freight forwarder', 'freight forwarding', 'cargo handler',
    'air cargo', 'sea cargo', 'sea freight', 'air freight',
    'ocean freight', 'international freight', 'domestic freight',
    'import export', 'clearance agent', 'quarantine service',
    'post office', 'auspost', 'australia post',
    'parcel delivery', 'pak & send', 'express post',
    'registered post', 'certified mail', 'priority mail',
    'bulk mail', 'direct mail', 'mail house', 'fulfilment',
    'distribution centre', 'distribution center',
    'warehouse service', 'warehousing', '3pl', 'third party logistics',
    '4pl', 'supply chain company', 'contract logistics',
    'dhl', 'fedex', 'ups', 'tnt', 'toll transport',
    'toll logistics', 'toll freight', 'star track', 'startrack',
    'couriers please', 'hunter express', 'border express',
    'direct couriers', 'fastway', 'aramex', 'allied express',
    'sendle', 'transdirect', 'temando', 'machship',
    'shippit', 'shipstation', 'easyship', 'freight quote',
    'cope sensitive freight', 'capital transport',
    'kings transport', 'mccolls transport', 'lindsay transport',
    'followmont', 'wettenhalls', 'simon national carriers',
    'ron finemore', 'scotts transport', 'nolan transport',
    'nqx', 'northline', 'century transport', 'cahill transport',
    'bunker freight', 'duttons transport', 'crawford transport',
    'colless transport', 'hewitt cattle transport',
    'elders transport', 'stock transport', 'livestock transport',
    'horse transport', 'float hire',
    'grants coachline', 'dubbo radio cabs',
    'scottys the movers', 'western bulk haulage',
    'itransport', 'traffic qld', 'reardon towing',
    'simmo logistics', 'stillus logistics', 'riverina traffic',
    'dynamic rail', 'proficient container', 'malwa fleet',
)

# ---- EDUCATION ----
rule('Education',
    'education', 'educational', 'school', 'kindergarten', 'preschool', 'pre-school',
    'childcare', 'child care', 'daycare', 'day care',
    'early learning', 'early childhood', 'elc centre',
    'family day care', 'fdc', 'occasional care', 'vacation care',
    'after school care', 'before school care',
    'outside school hours care', 'oshc',
    'creche', 'crèche', 'nursery school', 'playgroup', 'play group',
    'kindy', 'prep school', 'preparatory school',
    'primary school', 'elementary school', 'middle school',
    'intermediate school', 'secondary school', 'senior school',
    'high school', 'grammar school', 'college',
    'p-12', 'k-12', 'r-12', 'f-12', 'prep-12',
    'year 12', 'hsc', 'vce', 'qce', 'wace', 'sace', 'ncea',
    'ib school', 'international baccalaureate',
    'montessori', 'steiner', 'waldorf', 'reggio emilia',
    'university', 'university of', 'uni of', 'uni student',
    'tafe', 'technical college',
    'technical and further education', 'polytechnic',
    'institute of tech', 'institute of tafe',
    'vocational education', 'vet training',
    'higher education', 'tertiary education',
    'undergraduate', 'postgraduate', 'doctoral', 'phd program',
    'bachelors degree', 'diploma course', 'certificate course',
    'short course', 'micro-credential', 'mooc',
    'online learning', 'distance education', 'flexible learning',
    'blended learning', 'continuing education', 'lifelong learning',
    'adult education', 'adult learning', 'adult & community education',
    'community college', 'community learning',
    'neighbourhood house', 'community house',
    'training institute', 'training academy', 'training college',
    'training provider', 'training company', 'training group',
    'training solutions', 'traineeship', 'apprenticeship', 'apprentice',
    'trade school', 'skills training', 'workplace training',
    'workplace assessment', 'rto provider', 'registered training organisation',
    'registered training organization',
    'corporate training', 'professional development',
    'pd training', 'executive education', 'leadership development',
    'management training', 'sales training', 'compliance training',
    'safety training', 'induction training', 'onboarding program',
    'swim school', 'swimming school', 'swim academy', 'swimming academy',
    'swim centre', 'swimming centre', 'swim lesson', 'swimming lesson',
    'aquatic education', 'water safety program',
    'surf awareness', 'nippers', 'junior lifesaving',
    'learn to swim', 'swim coach', 'swimming coach',
    'dance school', 'dance academy', 'dance studio',
    'dance class', 'dance lesson', 'dance education',
    'music school', 'music academy', 'music lesson', 'music tutor',
    'music tuition', 'music education', 'music teacher',
    'music instructor', 'music coach', 'music studio',
    'tutor', 'tuition', 'coaching college', 'coaching school',
    'coaching academy', 'coaching centre', 'coaching center',
    'tri training', 'maxima training',
    'allegra school', 'action learning', 'little learners',
    'burgmann anglican school', 'zoomers swim school',
    'cairns kids elc', 'children first education',
    'love2swim school', 'leading childcare', 'warakirri college',
    'macallan college', 'minimbah state school',
    'learning links', 'little ducks childcare',
    'jump n swim academy', 'marsden state high school',
    'university of queensland', 'mackillop college',
    'st laurence\'s college', 'south west institute of tafe',
    'kirana education', 'crossways lutheran school',
    'wynnum west state school', 'holy spirit college',
    'dunmore lang college', 'eastbourne primary school',
    'chester hill kindergarten', 'marangaroo childcare',
    'sunrise childcare', 'springwood teaching',
    'mdeec',
)

# ---- PERSONAL CARE ----
rule('Personal Care',
    'barber', 'barbershop', 'barber shop', 'hair dresser', 'hairdresser',
    'hair cutting', 'hair stylist', 'hair styling', 'hair salon',
    'hair studio', 'hair design', 'hair bar', 'hair boutique',
    'hair fashion', 'hair trend',
    'beauty salon', 'beauty spa', 'beauty studio', 'beauty therapy',
    'beauty therapist', 'beauty clinic', 'beauty treatment',
    'beauty bar', 'beauty room', 'beauty parlour', 'beauty parlor',
    'beauty boutique', 'beauty centre', 'beauty center',
    'beauty lab', 'beauty lounge', 'beauty haven',
    'beauty oasis', 'beauty retreat', 'beauty sanctuary',
    'nails salon', 'nails spa', 'nails bar', 'nails studio',
    'nails beauty', 'nails art', 'nails design',
    'nails boutique', 'nails express', 'nails fashion',
    'manicure', 'pedicure', 'gel nails', 'acrylic nails',
    'shellac nails', 'sns nails', 'dip powder nails',
    'nail art', 'nail design', 'nail tech', 'nail technician',
    'nail specialist', 'nail enhancement', 'nail extension',
    'massage therapy', 'massage therapist', 'remedial massage',
    'relaxation massage', 'sports massage', 'deep tissue massage',
    'hot stone massage', 'aromatherapy massage', 'reflexology',
    'shiatsu massage', 'thai massage', 'swedish massage',
    'lymphatic drainage', 'myotherapy', 'bowen therapy',
    'craniosacral therapy',
    'day spa', 'spa retreat', 'spa treatment', 'spa therapy',
    'spa wellness', 'spa beauty', 'spa relaxation',
    'spa sanctuary', 'spa haven', 'spa oasis',
    'skin care clinic', 'skin therapy', 'skin treatment',
    'skin beauty', 'skin laser', 'skin aesthetic',
    'skin rejuvenation', 'skin renewal', 'skin health clinic',
    'skin specialist', 'skin doctor', 'skin centre', 'skin center',
    'skin lab', 'skin laboratory', 'skin studio', 'skin boutique',
    'waxing salon', 'waxing studio', 'waxing bar', 'waxing boutique',
    'threading salon', 'threading studio', 'threading bar',
    'henna design', 'mehndi', 'henna tattoo',
    'body art', 'face painting', 'makeup artist', 'make-up artist',
    'cosmetic tattoo', 'cosmetic injection clinic',
    'cosmetic studio', 'cosmetic beauty', 'cosmetic treatment',
    'lash extension', 'lash lift', 'lash perm', 'lash tint',
    'lash bar', 'lash studio', 'lash boutique', 'lash salon',
    'lash beauty', 'lash design', 'lash art',
    'lash heaven', 'lash paradise', 'lash oasis',
    'eyelash extension', 'eyelash lift', 'eyelash perm',
    'brow bar', 'brow studio', 'brow salon', 'brow beauty',
    'brow design', 'brow art', 'brow shaping', 'brow threading',
    'brow tint', 'microblading', 'brow feathering', 'brow ombré',
    'eyebrow bar', 'eyebrow studio', 'eyebrow salon',
    'eyebrow beauty', 'eyebrow design', 'eyebrow art',
    'eyebrow shaping', 'eyebrow threading', 'eyebrow tint',
    'tattoo studio', 'tattoo shop', 'tattoo parlour', 'tattoo parlor',
    'tattoo artist', 'tattoo art', 'tattoo design', 'tattoo removal',
    'piercing studio', 'piercing shop', 'piercing parlour', 'piercing parlor',
    'body piercing', 'body modification',
    'tanning salon', 'tanning studio', 'solarium',
    'spray tan', 'fake tan', 'fake bake', 'bronze studio',
    'bronze bar', 'bronze salon', 'bronze boutique', 'bronze tan',
    'laser clinic', 'laser hair removal', 'laser hair reduction',
    'laser skin clinic', 'laser skin treatment',
    'laser skin rejuvenation', 'laser skin renewal',
    'laser skin resurfacing', 'laser skin tightening',
    'laser tattoo removal', 'laser beauty', 'laser cosmetic',
    'laser aesthetic', 'laser dermal', 'ipl treatment',
    'intense pulsed light', 'light therapy', 'phototherapy',
    'photofacial',
    'aesthetic clinic', 'aesthetic beauty', 'aesthetic cosmetic',
    'aesthetic dermal', 'aesthetic injectable', 'aesthetic treatment',
    'aesthetic medicine', 'aesthetic doctor', 'aesthetic specialist',
    'aesthetic practitioner', 'aesthetic nurse', 'aesthetic centre',
    'aesthetic center', 'aesthetic studio', 'aesthetic boutique',
    'cosmetic clinic', 'cosmetic doctor', 'cosmetic nurse',
    'cosmetic practitioner', 'cosmetic specialist',
    'cosmetic surgeon', 'cosmetic surgery', 'cosmetic dermatology',
    'cosmetic beauty', 'cosmetic treatment', 'cosmetic injectable',
    'cosmetic injection', 'cosmetic filler', 'cosmetic botox',
    'anti-wrinkle treatment', 'anti-ageing treatment',
    'dermal clinic', 'dermal therapy', 'dermal therapist',
    'dermal treatment', 'dermal filler', 'dermal needling',
    'dermal rolling', 'dermal stamping', 'dermal planing',
    'dermal abrasion', 'dermal peel', 'dermal science',
    'dermal skin', 'dermal beauty', 'dermal cosmetic',
    'dermal aesthetic', 'dermal centre', 'dermal center',
    'dermal studio',
    'botox treatment', 'lip filler', 'cheek filler',
    'chin filler', 'jaw filler', 'temple filler',
    'under eye filler', 'tear trough filler',
    'nasolabial filler', 'marionette filler',
    'lip augmentation', 'cheek augmentation',
    'non-surgical rhinoplasty', 'non-surgical facelift',
    'thread lift', 'pdo thread', 'silhouette soft',
    'prp treatment', 'platelet rich plasma',
    'vampire facial', 'vampire facelift',
    'micro needling', 'microneedling', 'micro pen',
    'skinpen', 'dermapen', 'derma roller', 'dermaneedling',
    'collagen induction therapy', 'skin needling',
    'rf microneedling', 'morpheus rf', 'scarf rf',
    'thermage', 'ulthera', 'ultherapy', 'hifu',
    'high intensity focused ultrasound',
    'radiofrequency treatment', 'rf skin treatment',
    'rf facial', 'rf body treatment',
    'rf tightening', 'rf lifting', 'rf contouring',
    'sauna', 'float tank', 'float therapy', 'float spa',
    'float centre', 'float center', 'float studio',
    'float room', 'float pod', 'float cabin',
    'infrared sauna', 'steam room', 'steam bath',
    'ice bath', 'cold plunge', 'cryotherapy',
    'hydrotherapy', 'hydro spa', 'hydro pool',
    'hydro massage', 'jacuzzi', 'hot tub', 'spa bath',
    'spa pool', 'mineral pool', 'mineral spa',
    'magnesium pool', 'salt pool', 'salt room', 'salt cave',
    'halotherapy',
    'electrolysis hair', 'ipl hair removal',
    'basement barbers', 'money cuts barbers',
    'royal blends barbers', 'jezzys barber shop',
    'roha beauty salon', 'camilla nails',
    'urban retreat massage', 'elegance barber shop',
    'cornerstone barbers', 'eves skin and beauty',
    'two by the sea salon', 'nk barbers', 'ace of cuts barbers',
    'star nails & beauty', 'bravo barbers', 'kelly beauty care',
    'sweet touch spa',
)

# ---- UTILITIES ----
rule('Utilities',
    'electricity company', 'electricity provider', 'electricity retail',
    'electricity supply', 'electricity network',
    'electricity distribution', 'electricity transmission',
    'electricity generation', 'power company', 'power retail',
    'power network', 'power generation', 'power supply',
    'power distribution', 'power transmission',
    'energy australia', 'energy retail', 'energy provider',
    'energy company', 'energy distribution', 'energy supply',
    'energy network', 'energy generation', 'energy group',
    'agl energy', 'origin energy', 'energy australia',
    'simply energy', 'alinta energy', 'ergon energy',
    'synergy energy', 'powercor', 'citipower', 'ausgrid',
    'endeavour energy', 'essential energy', 'evoenergy',
    'actewagl', 'tasnetworks', 'aurora energy', 'energex',
    'sa power networks', 'western power', 'horizon power',
    'nt power and water', 'power and water',
    'snowy hydro', 'hydro tasmania', 'delta electricity',
    'transgrid', 'electranet', 'powerlink',
    'aemo', 'aemc', 'aer regulator',
    'water corporation', 'water authority', 'water board',
    'water utility', 'water retail', 'water supply',
    'water service', 'water billing',
    'sydney water', 'yarra valley water', 'south east water',
    'city west water', 'greater western water',
    'goulburn valley water', 'coliban water', 'barwon water',
    'central highlands water', 'wannon water',
    'east gippsland water', 'westernport water',
    'lower murray water', 'grampians water',
    'goulburn murray water', 'north east water',
    'gippsland water', 'south gippsland water', 'western water',
    'seqwater', 'seq water', 'urban utilities', 'unitywater',
    'logan water', 'redland water', 'gold coast water',
    'brisbane water', 'queensland urban utilities',
    'taswater', 'sa water', 'water corporation wa',
    'power and water nt', 'icon water', 'act water',
    'water nsw', 'nsw water',
    'sewerage service', 'waste water treatment',
    'recycled water', 'stormwater management',
    'gas company', 'gas retail', 'gas network',
    'gas supply', 'gas distribution', 'gas utility',
    'gas pipeline', 'gas transmission',
    'apa group', 'jemena', 'multinet',
    'australian gas networks', 'ausnet gas', 'gasnet',
    'allgas', 'tas gas', 'origin energy gas',
    'energy australia gas', 'agl gas',
    'waste management', 'waste collection', 'waste disposal',
    'waste transfer station', 'waste recycling',
    'rubbish collection', 'rubbish removal',
    'garbage collection', 'garbage truck',
    'skip bin', 'skip hire', 'bin hire',
    'wheelie bin', 'dumpster', 'landfill',
    'transfer station', 'resource recovery',
    'kerbside collection', 'kerbside recycling',
    'hard waste', 'green waste', 'organic waste',
    'food waste recycling', 'commercial waste',
    'industrial waste', 'construction waste',
    'cleanaway', 'suez', 'veolia', 'jj richards',
    'remondis', 'bingo industries', 'alex fraser',
    'council rates', 'council rate notice',
    'council fee', 'council charge', 'council permit',
    'shire council', 'city council', 'regional council',
    'town council', 'district council', 'municipal council',
    'gladstone area water', 'gladstone water board',
    'murweh shire', 'shire of coolgardie', 'carpentaria shire',
    'solar naturally',
    'advanced water', 'powerlink solutions',
)

# ---- TELECOMMUNICATIONS ----
rule('Telecommunications',
    'telecommunications', 'telecom company',
    'telstra', 'optus', 'vodafone', 'tpg telecom',
    'iinet', 'aussie broadband', 'dodo internet',
    'belong broadband', 'belong mobile',
    'exetel', 'superloop', 'mate communicate',
    'more telecom', 'flip connect', 'ausbbs', 'nodeone',
    'southern phone', 'commander phone',
    'myrepublic', 'spintel', 'amaysim', 'lebara',
    'aldimobile', 'aldimobile', 'boost mobile',
    'kogan mobile', 'felix mobile', 'moose mobile',
    'circles life', 'belong mobile', 'numobile',
    'yomojo', 'c mobile', 'hello mobile', 'pennytel',
    'mobile provider', 'mobile carrier', 'mobile network',
    'mobile plan', 'mobile service provider',
    'phone provider', 'phone carrier', 'phone network',
    'phone plan', 'phone service provider',
    'internet provider', 'internet service provider',
    'internet company', 'isp provider', 'isp company',
    'broadband provider', 'broadband plan', 'nbn provider',
    'nbn plan', 'fibre internet', 'adsl internet',
    'starlink internet', 'skymuster internet', 'skymesh',
    'activ8me', 'clear networks', 'uniti internet',
    'opticomm', 'open networks', 'redtrain', 'bred network',
    'lbnco', 'dgtek', 'tangerine internet', 'swoop internet',
    'launtel', 'canstar blue', 'origin broadband',
    'telstra broadband', 'optus broadband',
    'vodafone nbn', 'tpg internet', 'iinet broadband',
    'voip service', 'sip trunk', 'unified communications',
    'pabx', 'pbx', 'business phone system',
    'hosted pbx', 'cloud pbx', 'virtual pbx',
    'phone system', 'ip telephony', 'ip phone',
    'desk phone', 'conference phone', 'headset',
    'call centre solution', 'contact centre solution',
    'phone repair shop', 'phone repair store',
    'phone accessories store', 'phone case shop',
    'phone screen repair', 'phone screen replacement',
    'screen protector shop', 'phone charger store',
    'genius phone repairs', 'sos phone repairs',
    'phonetouch', 'advanced tel', 'phone fix',
    'mobile repair store', 'mobile fix store',
    'phone doctor', 'mobile doctor', 'phone hospital',
    'screen repair shop', 'screen replacement shop',
    'iphone repair', 'samsung repair', 'ipad repair',
    'tablet repair', 'laptop repair shop',
    'macbook repair', 'pc repair shop', 'computer repair shop',
    'australian mobile', 'mobile exchange',
    'mobile central', 'mobile monster', 'mobile citi',
    'all phones', 'phone zone', 'phone planet',
    'phone world', 'phone house', 'phone store',
    'mobile store', 'mobile shop',
    'data centre', 'data center', 'datacentre', 'datacenter',
    'colocation facility', 'co-location facility',
    'cloud hosting provider', 'cloud provider',
    'managed hosting',
    'nbn co', 'nbn company', 'nbn australia',
    'national broadband network',
    'vodafone australia', 'optus billing',
    'aldimobile', 'telstar telecommunications',
)

# ---- INSURANCE ----
rule('Insurance',
    'insurance company', 'insurance provider', 'insurance group',
    'insurance service', 'insurance broker', 'insurance agency',
    'insure', 'insured', 'insuring', 'underwriter', 'underwriting',
    'allianz', 'qbe insurance', 'nrma insurance', 'aami insurance',
    'youi insurance', 'suncorp insurance', 'comminsure',
    'covermore insurance', 'budget direct insurance',
    'gio insurance', 'apollo insurance', 'cgu insurance',
    'real insurance', 'tower insurance', 'hollard insurance',
    'chubb insurance', 'berkshire hathaway insurance',
    'iag insurance', 'insurance australia group',
    'rac insurance', 'racv insurance', 'racq insurance',
    'raa insurance', 'sgic insurance',
    'western qbe', 'elders insurance',
    'woolworths insurance', 'coles insurance', 'aldi insurance',
    'bupa insurance', 'medibank insurance', 'nib insurance',
    'hcf insurance', 'hbf insurance',
    'life insurance', 'life cover', 'death cover',
    'funeral cover', 'funeral plan', 'funeral insurance',
    'trauma insurance', 'trauma cover', 'tpd cover',
    'total permanent disability', 'income protection insurance',
    'disability insurance', 'critical illness cover',
    'terminal illness cover',
    'health insurance provider', 'private health insurance',
    'hospital cover', 'extras cover', 'ambulance cover',
    'ambulance insurance', 'dental insurance', 'optical insurance',
    'home insurance', 'home & contents', 'contents insurance',
    'building insurance', 'landlord insurance',
    'renters insurance', 'tenants insurance',
    'car insurance', 'motor insurance', 'vehicle insurance',
    'auto insurance', 'ctp insurance', 'compulsory third party',
    'green slip', 'comprehensive car insurance',
    'third party insurance', 'third party property',
    'fire & theft insurance', 'fire and theft insurance',
    'boat insurance', 'marine insurance', 'caravan insurance',
    'motorcycle insurance', 'scooter insurance',
    'travel insurance', 'pet insurance',
    'business insurance', 'commercial insurance',
    'professional indemnity insurance', 'public liability insurance',
    'product liability insurance', 'workers comp',
    'workers compensation', 'workcover', 'worksafe',
    'cyber insurance', 'management liability insurance',
    'directors & officers insurance', 'd&o insurance',
    'construction insurance', 'contract works insurance',
    'contractors all risks', 'plant & equipment insurance',
    'machinery breakdown insurance', 'business interruption insurance',
    'consequential loss insurance', 'key person insurance',
    'partnership insurance', 'shareholder protection insurance',
    'buy sell agreement insurance',
    'insurance broking', 'reinsurance',
)

# ---- RENT ----
rule('Rent',
    'real estate agent', 'real estate agency', 'realty',
    'property management', 'property manager', 'property group',
    'property agency', 'property sales', 'property rental',
    'property lease', 'property consultant', 'property advisory',
    'lj hooker', 'ray white', 'century 21', 're/max', 'remax',
    'harcourts', 'belle property', 'mcgrath estate',
    'elders real estate', 'first national real estate',
    'richardson & wrench', 'barry plant', 'woodard real estate',
    'davidson real estate', 'run property', 'little real estate',
    'jellis craig', 'marshall white', 'kay & burton',
    'colliers', 'cbre', 'jll', 'savills', 'knight frank',
    'cushman & wakefield', 'laing & simmons',
    'starr partners', 'independent property group',
    'stockdale & leggo', 'barry plant real estate',
    'buxton real estate', 'hockingstuart', 'woodards',
    'nelson alexander', 'jas stephens',
    'ratemyagent', 'homely', 'onthehouse', 'corelogic',
    'pricefinder', 'rp data', 'domain', 'realestate.com',
    'rental property', 'rental management', 'rental agency',
    'rental group', 'rental company', 'rental service',
    'rental home', 'rental house', 'rental apartment',
    'letting agent', 'letting agency', 'leasing agent', 'leasing agency',
    'conveyancer', 'conveyancing', 'settlement agent', 'settlement agency',
    'strata management', 'strata manager', 'body corporate management',
    'owners corporation', 'community title management',
    'share house rental', 'share accommodation',
    'flatmate', 'flatmates', 'roommate', 'roommates',
    'co-living', 'co living space',
    'student accommodation', 'student housing',
    'short term rental', 'short stay rental',
    'executive rental', 'corporate rental',
    'furnished rental', 'serviced apartment rental',
    'coastal letting co', 'real property wa', 'qualrent',
    'cohen handler', 'archibald investments',
)

# ---- GYMS AND OTHER MEMBERSHIPS ----
rule('Gyms and other memberships',
    'gym', 'fitness centre', 'fitness center', 'fitness club',
    'fitness studio', 'fitness first', 'plus fitness',
    'snap fitness', 'goodlife gym', 'goodlife health',
    'jets fitness', 'fernwood fitness', 'fernwood health',
    'genesis fitness', 'zap fitness', 'revo fitness',
    'anytime fitness', 'jett fitness', 'world gym',
    'crunch fitness', 'planet fitness', '9round',
    'ufc gym', 'fit n fast',
    'crossfit', 'f45 training', 'orange theory', 'orangetheory',
    'fitstop', 'bodyfit', 'vision pt', 'pt academy', 'pt studio',
    'personal training studio', 'group training', 'group fitness',
    'hiit class', 'hiit training', 'high intensity training',
    'boot camp', 'bootcamp', 'circuit training class',
    'boxing gym', 'boxing studio', 'boxing club',
    'muay thai gym', 'mma gym', 'bjj gym', 'brazilian jiu jitsu',
    'krav maga gym', 'karate dojo', 'taekwondo dojo',
    'martial arts school', 'martial arts academy',
    'martial arts studio', 'martial arts gym',
    'yoga studio', 'pilates studio', 'barre studio',
    'pole studio', 'aerial studio', 'reformer pilates',
    'hot yoga', 'bikram yoga', 'vinyasa yoga',
    'hatha yoga', 'ashtanga yoga', 'iyengar yoga',
    'kundalini yoga', 'yin yoga', 'restorative yoga',
    'power yoga', 'flow yoga', 'rocket yoga',
    'acro yoga', 'aerial yoga',
    'leisure centre', 'leisure center', 'aquatic centre',
    'aquatic center', 'recreation centre', 'recreation center',
    'swim centre', 'swim center', 'swimming pool',
    'public pool', 'community pool', 'indoor pool',
    'outdoor pool', 'wave pool', 'water slide park',
    'hydrotherapy pool', 'lap pool', '50m pool', 'olympic pool',
    'heated pool', 'chlorinated pool', 'salt water pool',
    'learn to swim pool', 'toddler pool', 'children\'s pool',
    'kiddie pool', 'splash park', 'spray park', 'water play park',
    'ymca centre', 'ymca recreation', 'ymca aquatic',
    'city leisure', 'belgravia leisure', 'bluefit',
    'health club', 'fitness club', 'country club',
    'racquet club', 'racquetball', 'squash court',
    'tennis court hire', 'badminton court hire',
    'indoor sports centre', 'indoor sports center',
    'sports complex', 'sports facility', 'sports hall',
    'climbing gym', 'climbing centre', 'climbing center',
    'climbing wall', 'bouldering gym', 'bouldering centre',
    'bouldering center', 'rock climbing indoor',
    'urban climb', 'hardrock climbing',
    'ice skating rink', 'ice rink', 'roller skating rink',
    'skate park', 'skatepark', 'skate ramp',
    'bmx track', 'bmx park', 'mountain bike park',
    'snow centre', 'ski centre', 'snow dome',
    'indoor ski', 'indoor snow',
    'membership fee', 'fitness membership',
    'gym membership', 'club membership',
    'leisure membership', 'recreation membership',
    'pool membership', 'swim membership',
    'alliance mma australia', 'inverell aquatic',
    'launceston aquatic', 'carnegie memorial',
    'gunyama park aquatic', 'albany creek leisure',
    'scc ulladulla leisure',
    'fernwood women\'s health club',
    'envision health and fitness',
)

# ---- FEES ----
rule('Fees',
    'interest charge', 'interest charges',
    'account keeping fee', 'account fee', 'monthly fee',
    'annual fee', 'service fee', 'bank fee',
    'late payment fee', 'late fee', 'overlimit fee',
    'overdraft fee', 'atm fee', 'transaction fee',
    'foreign currency fee', 'international transaction fee',
    'merchant service fee', 'establishment fee',
    'loan fee', 'account service fee',
    'dishonour fee', 'dishonour', 'direct debit fee',
)

# ---- INFORMATION ----
rule('Information',
    'information service', 'information centre', 'information center',
    'information technology', 'information system',
    'information solution', 'information management',
    'information group', 'information company',
    'newspaper', 'news publisher', 'news publishing', 'press agency',
    'magazine publisher', 'journal publisher', 'editorial service',
    'print media', 'media company', 'media group', 'media agency',
    'media monitor', 'media watch', 'media outlet', 'media network',
    'consulting', 'consultant', 'consultancy', 'advisory', 'advisor',
    'consulting firm', 'consulting group', 'consulting service',
    'business consulting', 'management consulting',
    'strategy consulting', 'it consulting',
    'hr consulting', 'marketing consulting',
    'accounting firm', 'accounting practice', 'accounting service',
    'accounting group', 'accounting company',
    'tax agent', 'tax accountant', 'tax return preparer',
    'tax service', 'tax practice', 'tax firm', 'tax specialist',
    'tax consultant', 'tax advisory',
    'bookkeeping', 'bookkeeper', 'bas agent', 'bas service',
    'auditor', 'audit firm', 'audit service', 'audit company',
    'audit group', 'audit practice',
    'financial planner', 'financial planning',
    'financial advice', 'financial advisor', 'financial advisory',
    'wealth management', 'wealth advisory',
    'smsf accountant', 'self managed super fund',
    'superannuation advice', 'superannuation service',
    'legal firm', 'legal practice', 'legal group',
    'legal service', 'legal office', 'legal company',
    'law firm', 'law practice', 'law group',
    'solicitor', 'barrister', 'attorney', 'lawyer',
    'notary', 'commissioner for declarations',
    'legal aid', 'community legal centre',
    'recruitment agency', 'recruitment company',
    'recruitment service', 'staffing agency',
    'employment agency', 'labour hire', 'labor hire',
    'temp agency', 'temp staff', 'personnel agency',
    'recruiting company', 'hr consulting',
    'hr service', 'hr solution', 'hr group', 'hr company',
    'software company', 'software development',
    'software solution', 'technology company',
    'technology group', 'technology solution',
    'tech company', 'tech group', 'tech startup',
    'saas company', 'cloud computing company',
    'cyber security company', 'cybersecurity company',
    'ai company', 'artificial intelligence company',
    'data science company', 'big data analytics',
    'business intelligence software',
    'it service provider', 'it solution provider',
    'it consulting firm', 'it support company',
    'managed it service', 'managed service provider',
    'it security company', 'it infrastructure company',
    'help desk service', 'service desk it',
    'it field service', 'it maintenance',
    'it backup service', 'it disaster recovery',
    'microsoft partner', 'azure cloud service',
    'aws partner', 'google cloud partner',
    'salesforce partner', 'sap partner',
    'marketing agency', 'advertising agency',
    'creative agency', 'digital agency', 'design agency',
    'branding agency', 'media agency', 'pr agency',
    'public relations agency', 'communications agency',
    'social media agency', 'content agency', 'seo agency',
    'sem agency', 'ppc agency', 'performance marketing agency',
    'growth marketing agency', 'marketing automation',
    'hubspot partner', 'market research', 'research company',
    'survey company', 'poll company', 'focus group',
    'data collection service', 'fieldwork research',
    'document management', 'document storage',
    'document shredding', 'document destruction service',
    'document scanning', 'document archiving',
    'document imaging', 'document digitization',
    'translation service', 'translating service',
    'interpreting service', 'interpreter agency',
    'translator service', 'language service provider',
    'multilingual service', 'localisation service',
    'signage company', 'sign maker', 'sign shop',
    'sign writing', 'graphic design', 'graphic designer',
    'design studio', 'print shop', 'printing company',
    'printer service', 'photocopying service',
    'digital print', 'offset print', 'large format print',
    'cnc machining', 'cnc routing', 'cnc milling',
    'cnc turning', '3d printing service',
    'laser cutting', 'laser engraving',
    'spt consultants', 'life choice solutions',
    'bunting group', 'randstad', 'chem tools',
    'titanium management', 'hazelrock',
    'platinum products', 'coast2coast group',
    'wilclean', 'vari-skilled', 'r and b mining',
    'bph wa', 'rn projects', 'ability enterprises',
    'austro services', 'arches enterprise',
    'allbreeds accounting', 'crestview lifestyle',
    'procycles hornsby', 'devine packaging',
    'ongc', 'b&d group', 'odum food group',
    'gidgee healing',
    'direct imports', 'roses only',
    'vuly play group', 'urban kitchens',
    'unique metals', 'total precast systems',
    'little miracles', 'chem tools',
    'itransport', 'adelaide premium', 'angliss',
    'messina', 'displayr australia', 'green life dispensary',
    'wildleaf dispensary',
    'firefighters calendar', 'calendar club australia',
    'wa credit union', 'department of finance',
    'roy morgan', 'ipsos', 'asa marketing',
    'records management', 'records storage',
    'corelogic', 'rp data', 'pricefinder',
    'pickles auctions', 'manheim auctions',
    'grays online', 'carnell business',
)

# ============================================================================
# CLASSIFICATION LOGIC
# ============================================================================

def classify_merchant(name, keywords, link, original_category):
    """
    Score all categories based on keyword matches.
    Return highest scoring category, with tie-breaking and safe fallback.
    """
    combined = f"{name} {keywords} {link}".lower()

    scores = Counter()
    for category, keyword_list in RULES:
        for kw in keyword_list:
            if kw in combined:
                scores[category] += 1

    if not scores:
        # No patterns matched → keep original if non-empty, else Information
        if original_category:
            return original_category
        return 'Information'

    # Get top categories
    top = scores.most_common()
    best_cat, best_score = top[0]

    # If original is empty, use best match (no need for high confidence)
    if not original_category:
        return best_cat

    # If best matches original, keep it
    if best_cat == original_category:
        return original_category

    # Check if original category also has matches
    original_score = scores.get(original_category, 0)

    # If original has zero matches, any better match wins (original was wrong)
    if original_score == 0 and best_score > 0:
        return best_cat

    # If both have matches, only override if best is significantly better (2+ more matches)
    if best_score >= original_score + 2:
        return best_cat

    # Keep original (not enough evidence to change)
    return original_category


def main():
    print("Loading merchant_kb.csv...")
    rows, fieldnames = load_csv(INPUT_FILE)
    print(f"Loaded {len(rows)} merchants")
    print(f"Loaded {len(RULES)} category rule groups")

    changes = []
    empty_filled = 0
    category_changed = 0
    unchanged = 0
    kept_original_filled = 0

    for i, row in enumerate(rows):
        name = row.get('merchant_name', '')
        keywords = row.get('keywords', '')
        link = row.get('link', '')
        original = row.get('category', '').strip()

        new_category = classify_merchant(name, keywords, link, original)

        if not original:
            if original != new_category:
                empty_filled += 1
                changes.append((i+2, name.strip(), original, new_category))
            else:
                kept_original_filled += 1
        elif original != new_category:
            category_changed += 1
            changes.append((i+2, name.strip(), original, new_category))
        else:
            unchanged += 1

        row['category'] = new_category

    # Write corrected file
    print(f"\nWriting corrected file to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8-sig', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"\n{'='*70}")
    print(f"RESULTS:")
    print(f"  Total merchants:                {len(rows)}")
    print(f"  Unchanged (correct):            {unchanged}")
    print(f"  Empty → filled with category:   {empty_filled}")
    print(f"  Wrong category fixed:           {category_changed}")
    print(f"  Total modifications:            {len(changes)}")
    print(f"{'='*70}")

    # Show changed categories (corrected wrong ones)
    if category_changed > 0:
        changed_only = [(r, n, o, nw) for r, n, o, nw in changes if o]
        print(f"\nCORRECTED CATEGORIES ({len(changed_only)} changes):")
        print(f"{'Row':<6} {'Merchant Name':<40} {'Old':<28} {'New':<28}")
        print(f"{'-'*6} {'-'*40} {'-'*28} {'-'*28}")
        for row_num, name, old, new in changed_only:
            display_name = name[:38] + '..' if len(name) > 40 else name
            print(f"{row_num:<6} {display_name:<40} {old:<28} {new:<28}")

    # Show newly filled categories (sample)
    if empty_filled > 0:
        filled_only = [(r, n, o, nw) for r, n, o, nw in changes if not o]
        print(f"\nFILLED EMPTY CATEGORIES ({len(filled_only)} filled):")
        print(f"{'Row':<6} {'Merchant Name':<40} {'Old':<28} {'New':<28}")
        print(f"{'-'*6} {'-'*40} {'-'*28} {'-'*28}")
        for row_num, name, old, new in filled_only[:100]:  # Show first 100
            display_name = name[:38] + '..' if len(name) > 40 else name
            print(f"{row_num:<6} {display_name:<40} {'(empty)':<28} {new:<28}")
        if len(filled_only) > 100:
            print(f"  ... and {len(filled_only) - 100} more (see output file)")

    # Final category distribution
    print(f"\n{'='*70}")
    print(f"FINAL CATEGORY DISTRIBUTION:")
    print(f"{'='*70}")
    cat_counts = Counter(row['category'] for row in rows)
    for cat, count in cat_counts.most_common():
        print(f"  {cat:<35} {count:>5}")


if __name__ == '__main__':
    main()


def process_categories(internal_path: Path = INTERNAL_FILE):
    internal_path = Path(internal_path)
    if not internal_path.exists():
        print(f"[categorize] {internal_path} not found")
        return None
    print(f"[categorize] Loading {internal_path}...")
    with open(internal_path, "r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    print(f"[categorize] Loaded {len(rows):,} rows  |  {len(RULES)} category rule groups")
    stats = Counter()
    empty_filled = 0
    category_changed = 0
    unchanged = 0
    for row in rows:
        name = row.get("merchant_name", "")
        keywords = row.get("keywords", "")
        link = row.get("link", "")
        original = row.get("category", "").strip()
        new_category = classify_merchant(name, keywords, link, original)
        if not original and new_category:
            empty_filled += 1
        elif original and original != new_category:
            category_changed += 1
        else:
            unchanged += 1
        row["category"] = new_category
    print(f"[categorize] Writing back to {internal_path}...")
    with open(internal_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=KB_INTERNAL_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    total = len(rows)
    print(f"\n[categorize] {'='*50}")
    print(f"  Total:              {total:>10,}")
    print(f"  Unchanged:          {unchanged:>10,}")
    print(f"  Empty filled:       {empty_filled:>10,}")
    print(f"  Category changed:   {category_changed:>10,}")
    cat_counts = Counter(row["category"] for row in rows)
    print(f"\n[categorize] Category distribution:")
    for cat, cnt in cat_counts.most_common():
        bar = "#" * max(1, cnt * 30 // max(total, 1))
        print(f"  {cat:<30} {cnt:>8,}  {bar}")
    return {"total": total, "unchanged": unchanged, "empty_filled": empty_filled, "category_changed": category_changed}

if __name__ == "__main__":
    process_categories()
